### ISSUE TITLE
Doesn't work with node 4.x

### ISSUE THREAD

**Issue by fallanic** [tk120404/node-rssparser#33]
Hi,

it looks like the lib doesn't work with recent nodejs versions : 

<pre>
Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/fallanic/work/testproject/node_modules/rssparser/node_modules/iconv/lib/iconv.js:27:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

</pre>

I tried deleting the package, and running npm install again, same problem.

Thanks in advance!

**Comment by fallanic** [comment]
It doesn't seem to work with 0.12.7 either

**Comment by polarity** [comment]
i forked the repo and removed the npm-shrinkwrap file which installed an old iconv module. this fixed the problem for me. until the repo owner is back online, you can install it straigt away from my github:

     npm install git+https://github.com/polarity/node-rssparser.git --save

**Comment by tk120404** [comment]
hi Polarity

Send a pull request
